displayName=Player NPC Replacer
author=Sensei
description=Shift-right-click a player or npc for an option to replace their model with an NPC's
tags=cosmetic,npc,player,replace,transform,model,visual
version=1.0.0
plugins=com.sensei.playernpcreplacer.PlayerNpcReplacerPlugin
build=standard